{{- if and .Values.llamastack.enabled .Values.llamastack.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: llamastack-test-v035
  namespace: {{ include "agentic-claims-demo.namespace" . }}
  labels:
    {{- include "agentic-claims-demo.labels" . | nindent 4 }}
    app: llamastack-v035
spec:
  {{- if .Values.llamastack.route.host }}
  host: {{ .Values.llamastack.route.host }}
  {{- else }}
  host: llamastack-test-v035-{{ .Values.global.namespace }}.{{ .Values.global.clusterDomain }}
  {{- end }}
  to:
    kind: Service
    name: llamastack-test-v035
    weight: 100
  port:
    targetPort: http
  {{- if .Values.llamastack.route.tls.enabled }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  {{- end }}
  wildcardPolicy: None
{{- end }}
